name: Java Build and Deploy (Ubuntu Runner)

on:
  push:
    branches:
      - '*'  # Trigger on all branches
  pull_request:
    branches:
      - '*'  # Trigger on pull requests for all branches

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use the Temurin JDK distribution
          java-version: '11'      # Specify the Java version (adjust as needed)

      # Step 3: Conditional Build and Deploy for Main Branch
      - name: Build and Deploy to Development Server
        if: github.ref_name == 'main'  # Build and deploy only for main branch
        run: |
          echo "Building artifact for main branch"
          mvn clean package
          echo "Deploying to Development Server"
          scp -i ${{ secrets.SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no target/*.war ${{ secrets.DEV_USER }}@${{ secrets.DEV_HOST }}:/opt/tomcat/webapps/
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no ${{ secrets.DEV_USER }}@${{ secrets.DEV_HOST }} <<EOF
            sudo /opt/tomcat/bin/shutdown.sh
            sudo /opt/tomcat/bin/startup.sh
          EOF

      # Step 4: Conditional Build and Deploy for Prod Branch
      - name: Build and Deploy to Production Server
        if: github.ref_name == 'prod'  # Build and deploy only for prod branch
        run: |
          echo "Building artifact for prod branch"
          mvn clean package
          echo "Deploying to Production Server"
          scp -i ${{ secrets.SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no target/*.war ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }}:/opt/tomcat/webapps/
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }} <<EOF
            sudo /opt/tomcat/bin/shutdown.sh
            sudo /opt/tomcat/bin/startup.sh
          EOF

      # Step 5: Conditional Build for Feature Branch
      - name: Build Artifact for Feature Branch
        if: startsWith(github.ref_name, 'feature/')  # Build only for feature branches
        run: |
          echo "Building artifact for feature branch"
          mvn clean package
          echo "Build completed. Artifact located in the target directory."
